local ADDON_NAME = ...
ShimmerTime = ShimmerTime or {}
local DS = ShimmerTime

DS.CATEGORIES = {
    {
        name = "Dimmer",
        enabledByDefault = false,
        emotes = {
            { key = "alt raid", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\altraid" },
            { key = "bustin", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\bustin", sound = "Interface\\AddOns\\ShimmerTime\\Sounds\\bustin.wav" },
            { key = "cream pie", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\cream" },
            { key = "dimmer", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\dimmer" },
            { key = "horse surgeon", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\horsesurgeon" },
            { key = "lexi", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\lexi" },
            { key = "milk it", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\milkit" },
            
        },
    },
    {
        name = "Shimmer",
        enabledByDefault = true,
        emotes = {
            { key = "apride", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\alliancepride", sound = "Interface\\AddOns\\ShimmerTime\\Sounds\\gay.wav" },
            { key = "birds", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\birds", sound = "Interface\\AddOns\\ShimmerTime\\Sounds\\birds.wav" },
            { key = "couchman", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\couchman" },
            { key = "hpride", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\hordepride", sound = "Interface\\AddOns\\ShimmerTime\\Sounds\\gay.wav" },
            { key = "ice cream", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\icecream" },
            { key = "shimmer", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\icon" },
            { key = "wow token", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\wowtoken", sound = "Interface\\AddOns\\ShimmerTime\\Sounds\\money.wav" },

        },
    },
    {
        name = "Shimmer Gifs",
        enabledByDefault = false,
        emotes = {
            {
                key = "pascal",
                texture = "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal.tga",
                frames = {
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_01.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_02.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_03.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_04.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_05.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_06.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_07.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_08.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_09.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_10.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_11.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_12.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_13.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_14.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_15.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_16.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_17.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_18.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_19.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pascal_20.tga",
                },
                frameDuration = 0.08,
            },
            {
                key = "pikachu",
                texture = "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu.tga",
                frames = {
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_01.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_02.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_03.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_04.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_05.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_06.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_07.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_08.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_09.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_10.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_11.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_12.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_13.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_14.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_15.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_16.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_17.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_18.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_19.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_20.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_21.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_22.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_23.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_24.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_25.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_26.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_27.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_28.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_29.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_30.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_31.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_32.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_33.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_34.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_35.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_36.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_37.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_38.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_39.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_40.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_41.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_42.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_43.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_44.tga",
                    "Interface\\AddOns\\ShimmerTime\\Gifs\\pikachu_45.tga",
                },
                frameDuration = 0.08,
            },
        },
    },
    {
        name = "Shimmer Pets",
        enabledByDefault = true,
        emotes = {
            { key = "kyber", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\kyber" },
            { key = "lilly", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\lilly" },
            { key = "rebel", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\rebel" },
            { key = "rudy", texture = "Interface\\AddOns\\ShimmerTime\\Emotes\\rudy" },
        },
    },
}

