local ADDON_NAME = ...
ShimmerTime = ShimmerTime or {}
local DS = ShimmerTime

DS.SHIMMER_QUOTES = {
    "\"I see 20 clouds but they're me\" - Ceeby",
    "\"Memeing on the chance of a miracle\" - Marshall",
    "\"I've got a lot of holes in my back\" - Ceeby",
    "\"It feels very weird in the mouth\" - Fae",
    "\"Dicks out for the drugs.\" - Casstastrophe",
    "\"I fucking hate architects\" - Fae",
    "\"I actively stand in the balls\" - Cloudywix",
    "\"It's only weird if you make it weird\" - Korea",
    "\"I'm a kid in Walmart looking for their mother\" - Utsu",
    "\"Local druid in Dornogal beefing with a butterfly\" - Marshall",
    "\"Hey! I'm gay here!\" - Korea",
    "\"Wow! I have a very clean mouth!\" - Korea",
    "\"You put me in the cone of shame, I love it\" - Korea",
    "\"I wish I was witty enough to come up with something witty\" - Utsu",
    "\"I'm so high, there is only Ra!\" - Ceeby",
    "\"He pees on my bed, he drinks my alcohol\" - Marshall",
    "\"don't go too far, the trees are real\" - Dangol",
    "\"we just really love mayonnaise\" - Marshall",
    "\"Some humans have normal human names?\" - Cass",
    "\"Eating kiwis are like eating a hedgehog, you know... a little furry...\" - Korea",
    "\"That really depends on the foxy grandpa we're talking about.\" - Marshall",
    "\"I keep getting knocked-up by bugs!\" - Fae",
    "\"That's what gets me so hard\" - Cass",
    "\"I lick people when they aren't paying attention.\" - Cass",
    "\"Mathematically go fuck yourself\" - Zoobus",
    "\"I didn't even think of you as a person-\" - Casstastrophe",
    "\"I haven't gotten any further since I got naked.\" - Dangol'",
    "\"sometimes my fingers just do things i don't want them to do\" - Dangol'",
    "\"that'll hold up in court bud\" - Chet Wallaby (CagedRat)",
    "\"I have faith in Greek Yogurt Nut.\" - Casstastrophe",
    "\"That's evil I like that\" - Casstastrophe",
    "\"I'm drawn like a moth to flame to the chud hated\" - Me",
    "\"Holy shit daddy!\" - Casstastrophe",
    "\"Are you saying that the Burning of Teldrassil is the Azeroth equivalent of 9/11?\" - Marble (Vel)",
    "\"Yes, yes I am.\" - ceebs",
    "\"Instead of a glass half empty or a glass half full, it's just a glass.\" - Zoeeeeeeeeee",
    "\"I think i took too many of those Mushrooms\" - Lucavex",
    "\"I'm literally missing feet.\" - Zoeeeeeeeeee",
    "\"She's so good about letting me put my fingers in her mouth\" - Viktoria",
    "\"I shit on people for fun\" - Casstastrophe",
    "\"Overload my ass, we took all your balls, bitch\" - Lucavex",
    "\"So, how'd you get so good at sucking dick? Deep-throating long Arby's curly fries.\" - Gabbee",
    "\"Breathing, underrated\" - Kinrok",
    "\"I don't think when I'm playing\" - Kinrok",
    "\"I'm uncomfortable with the fact that you're yellow.\" - Casstastrophe",
    "\"Thanks for changing your opinion from it's easy to it's hard couch man.\" - Vera",
    "\"Paulie will you plug your dongle into my hole?\" - Korea",
    "\"I'm fucking... they're behind.\" - Lilennia (lexibuns)",
    "\"I got the ultra-extension. No one can stop me now\" - Lilennia (lexibuns)",
    "\"I've got the clap.\" - Lilennia (lexibuns)",
    "\"who threatens someone with sex? ........wait i guess a rapist nevermind\" - Kinrok",
    "\"we gota RE un Disable\" - Kinrok",
    "\"THROW THE RAT AT THE LEVER\" - Ixie",
    "'I just have night elf ass in my face - Dangol'",
    "What happens on the therapy couch, stays on the therapy couch - Lexi",
}
